import type { Metadata } from "next";
import { Geist, Geist_Mono , Kanit  } from "next/font/google";
import "./globals.css";
import NavbarLeft from "@/components/navbar/NavbarLeft";
import HiddentNav from "../components/navbar/HiddentNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistKanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistKanit.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="lg:flex gap-3 ">
         {/* อยู่ทุกหน้า */}
          <div className=" bg-amber-600  sticky z-0 ">
            <HiddentNav />
            <NavbarLeft  />     
          </div>
            {/* อยู่ทุกหน้า */}
          <main className="flex-1 bg-white min-h-screen w-auto p-3">
            {children}      
          </main>
        </div>
      </body>
    </html>
  );
}
            
