import type { Metadata } from "next";
import { Geist, Geist_Mono , Kanit  } from "next/font/google";
import "./globals.css";
import NavbarLeft from "@/components/home/NavbarLeft";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistKanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistKanit.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="md:flex gap-3 ">
          <div className=" bg-amber-600  sticky z-0 ">
            <div className="  absolute z-1 flex md:flex-col justify-center items-center w-full h-full">
              <div>Romance</div>
              <div>Scient</div>
              <div>Technology</div>
              <div>History</div>
              <div>Generally</div>
            </div>
            <NavbarLeft  />       {/* อยู่ทุกหน้า */}
          </div>
          <main className="flex-1 bg-white min-h-screen w-auto">
            {children}      
          </main>
        </div>
      </body>
    </html>
  );
}
