import type { Metadata } from "next";
import { Geist, Geist_Mono , Kanit  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistKanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistKanit.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex flex-col justify-between">
         {/* อยู่ทุกหน้า */}
          <div className=" fixed z-99 w-full ">
            <Navbar  />     
          </div>
            {/* อยู่ทุกหน้า */}
          <main className=" min-h-screen w-full pt-5 absolute md:mt-12 mt-7  ">
            {children}      
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
            
